### ISSUE TITLE
Renaming Environment from ExercismSwift due to conflict with SwiftUI Environment

### ISSUE THREAD

**Issue by cedricbahirwe** [apps-fab/ExercismSwift#11]

**Comment by angiemugo** [comment]
Hi @cedricbahirwe I don't understand this issue. Please give a more detailed description

**Comment by cedricbahirwe** [comment]
Sure, currently when using the [Environment](https://developer.apple.com/documentation/swiftui/environment) property wrapper from SwiftUI in our Exercism app, the compiler throws the error below; that's because we are importing the `ExercismSwift` package into the file while it also contains a type alias name `Environment` which creates an ambiguity for the compiler since it can not figure out the correct.
<img width="935" alt="Screenshot 2024-01-10 at 19 58 33" src="https://github.com/apps-fab/ExercismSwift/assets/49038614/46ef1b17-e543-4875-829c-823ff17bb115">

<img width="836" alt="Screenshot 2024-01-10 at 19 59 43" src="https://github.com/apps-fab/ExercismSwift/assets/49038614/ef4ac080-36e6-45a4-bd5d-9a7fab5439cf">

Currently, the fix is to prefix it with the right Module name, `SwiftUI` in this case, for the error to disappear. I think the ideal solution could be to rename the type alias to avoid this conflict. Hope you understand the issue better now,
<img width="725" alt="Screenshot 2024-01-10 at 20 02 52" src="https://github.com/apps-fab/ExercismSwift/assets/49038614/05f12b39-efc2-4bb9-b5e9-40efeb594e72">

**Comment by cedricbahirwe** [comment]
The same applies to `Task` from `_Concurrency`, vs `Task` from ExercismSwift:


<img width="961" alt="Screenshot 2024-01-11 at 10 17 16" src="https://github.com/apps-fab/ExercismSwift/assets/49038614/20c0065d-a653-44c0-9b51-594fe0b16c72">


<img width="828" alt="Screenshot 2024-01-11 at 10 17 35" src="https://github.com/apps-fab/ExercismSwift/assets/49038614/09ed4cbd-56f6-4287-9f39-7251b95f47d7">

**Comment by angiemugo** [comment]
gotcha. Lemme fix those

**Comment by angiemugo** [comment]
@cedricbahirwe you can check the PR [here](https://github.com/apps-fab/ExercismSwift/pull/12)
